In [36]:
import itertools
import sympy as sy
import numpy as np
from sympy import I, Matrix
from scipy import signal, ndimage 

In [2]:
from utils import plot_pdf

In [3]:
# doc = fitz.open('Blahut_2010_Fast algorithms for signal processing.pdf')

In [16]:
f = np.arange(6)

In [17]:
w = np.arange(6)

In [19]:
np.convolve(f, w)

array([ 0,  0,  1,  4, 10, 20, 35, 44, 46, 40, 25])

In [21]:
f.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
w1 = np.array([0, 1, 2, 0, 0, 0])

In [46]:
output = ndimage.convolve(f.reshape(2, 3), w.reshape(2, 3), mode='constant', cval=0.0)
output

array([[ 6, 20, 26],
       [24, 46, 40]])

In [41]:
signal.convolve2d(f.reshape(2, 3), w.reshape(2, 3)[::-1, ::-1])

array([[ 0,  5, 14, 11,  6],
       [15, 34, 55, 34, 15],
       [ 6, 11, 14,  5,  0]])

In [44]:
np.multiply(f.reshape(2, 3), w.reshape(2, 3)[0])a

array([[ 0,  1,  4],
       [ 0,  4, 10]])

In [31]:
output = convolve(f.reshape(2, 3), w1.reshape(2, 3)[::-1, ::-1])
output

array([[ 2,  5,  6],
       [11, 14, 15]])

In [4]:
x = sy.symbols("x")
x

x

In [5]:
root = sy.solve(x**2+1, x)
sy.Matrix(root)

Matrix([
[-I],
[ I]])

In [6]:
prod = np.prod([x+r for r in root])
prod

(x - I)*(x + I)

In [7]:
sy.expand(prod)

x**2 + 1

In [8]:
root = sy.solve(x**3+1, x)
sy.Matrix(root)

Matrix([
[               -1],
[1/2 - sqrt(3)*I/2],
[1/2 + sqrt(3)*I/2]])

In [9]:
sy.expand((x+1)*(x+I)*(x-I))

x**3 + x**2 + x + 1

In [10]:
factor = sy.factor(x**3+1, modulus=17)
factor

(x + 1)*(x**2 - x + 1)

In [11]:
root = sy.solve(x**3+1, x)
sy.Matrix(root)

Matrix([
[               -1],
[1/2 - sqrt(3)*I/2],
[1/2 + sqrt(3)*I/2]])

In [12]:
360/60


6.0

In [13]:
root = np.roots([1, -1, -1, 1, -1, -1, -1])
sy.Matrix(root)

Matrix([
[                        1.66489196034509],
[ 0.627969351037362 + 0.903545493672716*I],
[ 0.627969351037362 - 0.903545493672716*I],
[                       -1.16201635911299],
[-0.379407151653412 + 0.531953440317594*I],
[-0.379407151653412 - 0.531953440317594*I]])

In [14]:
root = x + I
root

x + I

In [15]:
sy.conjugate(root)

conjugate(x) - I

In [16]:
e = root * sy.conjugate(root)
e

(x + I)*(conjugate(x) - I)

In [17]:
sy.expand((x + I)*(x - I))

x**2 + 1

In [18]:
sy.expand((x**2 + 1*I)*(x**2 - 1*I))

x**4 + 1

In [19]:
sy.expand((x + 1 + I)*(x + 1 - I))

x**2 + 2*x + 2

In [20]:
factor = sy.factor(x**2+1, domain ='CC')
factor

1.0*x**2 + 1.0

In [21]:
sy.expand((x + I)*(x - I))

x**2 + 1

In [22]:
num = 4

In [23]:
d = sy.Matrix(sy.symbols(" ".join(f"d_{i}"for i in range(num))))
d

Matrix([
[d_0],
[d_1],
[d_2],
[d_3]])

In [24]:
g = sy.Matrix(sy.symbols(" ".join(f"g_{i}"for i in range(num))))
g

Matrix([
[g_0],
[g_1],
[g_2],
[g_3]])

In [25]:
dx = sum([i*x**e for e, i in enumerate(d)])
dx

d_0 + d_1*x + d_2*x**2 + d_3*x**3

In [26]:
gx = sum([i*x**e for e, i in enumerate(g)])
gx

g_0 + g_1*x + g_2*x**2 + g_3*x**3

In [27]:
sx = gx*dx
sx

(d_0 + d_1*x + d_2*x**2 + d_3*x**3)*(g_0 + g_1*x + g_2*x**2 + g_3*x**3)

In [28]:
sxe = sy.expand(sx)
sxe

d_0*g_0 + d_0*g_1*x + d_0*g_2*x**2 + d_0*g_3*x**3 + d_1*g_0*x + d_1*g_1*x**2 + d_1*g_2*x**3 + d_1*g_3*x**4 + d_2*g_0*x**2 + d_2*g_1*x**3 + d_2*g_2*x**4 + d_2*g_3*x**5 + d_3*g_0*x**3 + d_3*g_1*x**4 + d_3*g_2*x**5 + d_3*g_3*x**6

In [29]:
sxec = sy.collect(sxe, x)
sxec

d_0*g_0 + d_3*g_3*x**6 + x**5*(d_2*g_3 + d_3*g_2) + x**4*(d_1*g_3 + d_2*g_2 + d_3*g_1) + x**3*(d_0*g_3 + d_1*g_2 + d_2*g_1 + d_3*g_0) + x**2*(d_0*g_2 + d_1*g_1 + d_2*g_0) + x*(d_0*g_1 + d_1*g_0)

In [30]:
sy.expand((x*d[1]*g[1] + I*d[0]*g[0])*(x*d[1]*g[1] - I*d[0]*g[0]))

d_0**2*g_0**2 + d_1**2*g_1**2*x**2

In [31]:
Matrix(np.convolve((x*d[1]*g[1], +I*d[0]*g[0]), (x*d[1]*g[1], - I*d[0]*g[0])))

Matrix([
[d_1**2*g_1**2*x**2],
[                 0],
[     d_0**2*g_0**2]])

In [32]:
z = sy.Matrix(sy.symbols(" ".join(f"z_{i}"for i in range(num))))
z

Matrix([
[z_0],
[z_1],
[z_2],
[z_3]])

Equivalência $x^2+1$

In [33]:
root = sy.solve(x**2+1, x)
sy.Matrix(root)

Matrix([
[-I],
[ I]])

In [34]:
sy.expand((x + I)*(x - I))

x**2 + 1

In [35]:
Matrix(np.convolve((x, +I), (x, - I)))

Matrix([
[x**2],
[   0],
[   1]])

In [36]:
Matrix(np.convolve((x*d[1], + I*d[0]), (x*g[1], - I*g[0])))

Matrix([
[             d_1*g_1*x**2],
[I*d_0*g_1*x - I*d_1*g_0*x],
[                  d_0*g_0]])

In [37]:
Matrix(np.convolve((d[1], d[0]), (g[1], g[0])))

Matrix([
[          d_1*g_1],
[d_0*g_1 + d_1*g_0],
[          d_0*g_0]])

Equivalência $x^4+1$

In [38]:
sy.expand((x**2 + x + I)*(x**2 + x - I))

x**4 + 2*x**3 + x**2 + 1

In [39]:
Matrix(np.convolve((x**2, x, +I), (x**2, x, - I)))

Matrix([
[  x**4],
[2*x**3],
[  x**2],
[     0],
[     1]])

In [40]:
Matrix(np.convolve((x**2*d[2], x*d[1], + I*d[0]), (x**2*g[2], x*g[1], - I*g[0])))

Matrix([
[                                  d_2*g_2*x**4],
[                   d_1*g_2*x**3 + d_2*g_1*x**3],
[I*d_0*g_2*x**2 + d_1*g_1*x**2 - I*d_2*g_0*x**2],
[                     I*d_0*g_1*x - I*d_1*g_0*x],
[                                       d_0*g_0]])

In [41]:
Matrix(np.convolve((d[2], d[1], d[0]), (g[2], g[1], g[0])))

Matrix([
[                    d_2*g_2],
[          d_1*g_2 + d_2*g_1],
[d_0*g_2 + d_1*g_1 + d_2*g_0],
[          d_0*g_1 + d_1*g_0],
[                    d_0*g_0]])

In [42]:
sy.expand((x + I)*(x - I)*(x + I)*(x - I)*(x + I)*(x - I)*(x + I)*(x - I))

x**8 + 4*x**6 + 6*x**4 + 4*x**2 + 1

In [43]:
t = sy.expand((x + I)*(x + I))
t

x**2 + 2*I*x - 1

In [44]:
sy.expand((x**2 + x + I)*(x**2 + x - I))

x**4 + 2*x**3 + x**2 + 1

In [45]:
t = sy.expand((x**2 + x + I)*(x**2 + x - I)*(x**2 - x + I)*(x**2 - x - I))
t

x**8 - 2*x**6 + 3*x**4 + 2*x**2 + 1

In [46]:
def multiplication_trick(x0, x1, y0, y1):
    m0 = x0*y0
    m2 = x1*y1
    m1 = (x0 + x1)*(y0 + y1) - m0 - m2
    return (m0, m1, m2)

In [47]:
multiplication_trick(1, 2, 1, 2)

(1, 4, 4)

In [48]:
np.convolve([1, 2], [1, 2])

array([1, 4, 4])

In [49]:
z0=(x**2 + x + 1)
z1=(x**2 + x - 1)
z2=(x**2 - x + 1)
z3=(x**2 - x - 1)


In [50]:
z0=(x + I)
z1=(x - I)
z2=(x + 1)
z3=(x - 1)


In [51]:
Matrix(multiplication_trick(z0, z1, z2, z3))

Matrix([
[                           (x + 1)*(x + I)],
[4*x**2 - (x - 1)*(x - I) - (x + 1)*(x + I)],
[                           (x - 1)*(x - I)]])

In [52]:
from blahut_collection_cyclic_convolution import matrices

In [53]:
n_cyclic = 2

In [54]:
a2_mtx = sy.Matrix(matrices[n_cyclic]["a"])
a2_mtx

Matrix([
[1,  1],
[1, -1]])

In [55]:
b2_mtx = sy.Matrix(matrices[n_cyclic]["b"])
b2_mtx

Matrix([
[1,  1],
[1, -1]])

In [56]:
g2_mtx = sy.Matrix([sy.Rational(*matrices[n_cyclic]["gr"])]*(b2_mtx.shape[0]))
g2_mtx

Matrix([
[1/2],
[1/2]])

In [57]:
bg2_mtx = sy.Matrix(np.multiply(g2_mtx, b2_mtx))
bg2_mtx

Matrix([
[1/2,  1/2],
[1/2, -1/2]])

In [58]:
bbg2_mtx = sy.diag(*(bg2_mtx * Matrix(g.flat()[:2])).flat())
bbg2_mtx

Matrix([
[g_0/2 + g_1/2,             0],
[            0, g_0/2 - g_1/2]])

In [59]:
(bg2_mtx * Matrix(g.flat()[:2])).tolist()

[[g_0/2 + g_1/2], [g_0/2 - g_1/2]]

In [60]:
c2_mtx = sy.Matrix(matrices[n_cyclic]["c"])
c2_mtx

Matrix([
[1,  1],
[1, -1]])

In [61]:
se = sy.MatMul(c2_mtx, bbg2_mtx, a2_mtx, Matrix(d.flat()[:2]), evaluate=False)
se

Matrix([
[1,  1],
[1, -1]])*Matrix([
[g_0/2 + g_1/2,             0],
[            0, g_0/2 - g_1/2]])*Matrix([
[1,  1],
[1, -1]])*Matrix([
[d_0],
[d_1]])

In [62]:
se = sy.MatMul(c2_mtx, bbg2_mtx, a2_mtx, Matrix(d.flat()[:2]), evaluate=True)
se

Matrix([
[d_0*g_0 + d_1*g_1],
[d_0*g_1 + d_1*g_0]])

In [63]:
bbg2_mtx * Matrix(d.flat()[:2])

Matrix([
[d_0*(g_0/2 + g_1/2)],
[d_1*(g_0/2 - g_1/2)]])

In [64]:
Matrix(d.flat()[:2])

Matrix([
[d_0],
[d_1]])

In [65]:
def multiplication_trick2(x0, x1, y0, y1):
    ax0 = x0+x1
    ax1 = x0-x1
    bx0 = (y0+y1)/2
    bx1 = (y0-y1)/2

    m0 = ax0*bx0
    m1 = ax1*bx1
    s0 = m0 + m1
    s1 = m0 - m1
    return (s0, s1, m1, m0)

In [66]:
np.convolve([1, 2], [1, 2])

array([1, 4, 4])

In [67]:
multiplication_trick2(1, 2, 1, 2)

(1.0, 5.0, 4.0, 0.5, 4.5)

In [68]:
np.convolve([3, 7], [2, 5])

array([ 6, 29, 35])

In [69]:
multiplication_trick2(3, 7, 2, 5)

(12.0, 41.0, 29.0, 6.0, 35.0)

In [70]:
np.convolve([8, 2], [11, 17])

array([ 88, 158,  34])

In [71]:
multiplication_trick2(8, 2, 11, 17)

(-36.0, 122.0, 158.0, -18.0, 140.0)