In [1]:
import numpy as np
import sympy as sy
from scipy import signal
from scipy import datasets
from matplotlib import pyplot as plt

In [2]:
from naive_convolve import naive_convolve
from fast_convolution import C3x3_5m20a9e
from utils import plot_pdf, symmetrical_cyclic_convolution

In [4]:
data = np.arange(5*5).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
kernel = np.array([
    [ 1, 2, 1],
    [ 2, 1, 2],
    [ 1, 2, 1],
])

In [6]:
output = signal.convolve2d(data, kernel, mode='valid')

In [7]:
output

array([[ 78,  91, 104],
       [143, 156, 169],
       [208, 221, 234]])

In [8]:
output_naive = naive_convolve(data, kernel)

In [9]:
output_naive

array([[ 78,  91, 104],
       [143, 156, 169],
       [208, 221, 234]])

In [10]:
fv = list(reversed(data[0].tolist()))
fv

[4, 3, 2, 1, 0]

In [11]:
kernel[0].tolist()

[1, 2, 1]

In [12]:
fast_conv = C3x3_5m20a9e(kernel[0].tolist())

In [23]:
fast_conv([2, 1, 0, 0, 0])

Matrix([
[4],
[1],
[0]])