In [1]:
import numpy as np
import sympy as sy
from scipy import signal
from scipy import datasets
from matplotlib import pyplot as plt

In [2]:
from naive_convolve import naive_convolve

In [3]:
import convolution_matrices
from utils import plot_pdf, symmetrical_cyclic_convolution

In [4]:
data = np.arange(5*5).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
kernel = np.array([
    [ 1, 2, 1],
    [ 2, 1, 2],
    [ 1, 2, 1],
])

In [6]:
output = signal.convolve2d(data, kernel, mode='valid')

In [7]:
output

array([[ 78,  91, 104],
       [143, 156, 169],
       [208, 221, 234]])

In [8]:
output_naive = naive_convolve(data, kernel)

In [9]:
output_naive

array([[ 78,  91, 104],
       [143, 156, 169],
       [208, 221, 234]])

In [25]:
a = np.array([
    [1, 0, 0],
    [1, 1, 1],
    [1, -1, 1],
    [1, 2, 4],
    [0, 0, 1]
])
b = a
gg = np.array([1/2, -1/2, -1/6, 1/6, 1])
c = np.array([
    [2, 0, 0, 0, 0],
    [-1, -2, 2, -1, 2],
    [-2, -1, -3, 0, -1],
    [1, 1, 1, 1, -2],
    [0, 0, 0, 0, 1]
])

In [79]:
f = np.flip(np.expand_dims(data[0][:c.shape[0]], 0))
f

array([[4, 3, 2, 1, 0]])

In [37]:
g = np.expand_dims(kernel[0], 0)
g

array([[1, 2, 1]])

In [41]:
bg = np.matmul(np.diag(gg), b)
bg

array([[ 0.5       ,  0.        ,  0.        ],
       [-0.5       , -0.5       , -0.5       ],
       [-0.16666667,  0.16666667, -0.16666667],
       [ 0.16666667,  0.33333333,  0.66666667],
       [ 0.        ,  0.        ,  1.        ]])

In [42]:
bg = np.matmul(np.diag(gg), b) * g
bg

array([[ 0.5       ,  0.        ,  0.        ],
       [-0.5       , -1.        , -0.5       ],
       [-0.16666667,  0.33333333, -0.16666667],
       [ 0.16666667,  0.66666667,  0.66666667],
       [ 0.        ,  0.        ,  1.        ]])

In [74]:
f

array([[0, 1, 2, 3, 4]])

In [57]:
c.T

array([[ 2, -1, -2,  1,  0],
       [ 0, -2, -1,  1,  0],
       [ 0,  2, -3,  1,  0],
       [ 0, -1,  0,  1,  0],
       [ 0,  2, -1, -2,  1]])

In [80]:
cf = c.T * f
cf

array([[ 8, -3, -4,  1,  0],
       [ 0, -6, -2,  1,  0],
       [ 0,  6, -6,  1,  0],
       [ 0, -3,  0,  1,  0],
       [ 0,  6, -2, -2,  0]])

In [81]:
cf.shape

(5, 5)

In [82]:
bg_cf = np.matmul(cf, bg)
bg_cf

array([[ 6.33333333,  2.33333333,  2.83333333],
       [ 3.5       ,  6.        ,  4.        ],
       [-1.83333333, -7.33333333, -1.33333333],
       [ 1.66666667,  3.66666667,  2.16666667],
       [-3.        , -8.        , -4.        ]])

In [84]:
np.matmul(a.T, bg_cf).sum(axis=0)

array([22., 39., 18.])

In [68]:
np.convolve(data[0], kernel[0], mode='valid')

array([ 4,  8, 12])