In [1]:
import numpy as np
from scipy import signal
from scipy import datasets
from matplotlib import pyplot as plt

In [2]:
from naive_convolve import naive_convolve

In [3]:
data = np.arange(5*5).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
kernel = np.array([
    [ 0, 1, 0],
    [ 1, 2, 1],
    [ 0, 1, 0],
])

In [5]:
output = signal.convolve2d(data, kernel, mode='valid')

In [6]:
output

array([[ 36,  42,  48],
       [ 66,  72,  78],
       [ 96, 102, 108]])

In [7]:
output_naive = naive_convolve(data, kernel)

In [8]:
output_naive

array([[ 36,  42,  48],
       [ 66,  72,  78],
       [ 96, 102, 108]])