In [2]:
import numpy as np

In [94]:
x = np.array([1, 2, 3])
y = np.array([7, 8, 9])

In [95]:
# x = np.array([3, 2, 1, 0, 0])
# y = np.array([5, 3, 7, 1, 2])

In [96]:
c = np.convolve(x, y)

In [97]:
c

array([ 7, 22, 46, 42, 27])

In [10]:
np.dot(x, y[::-1])

46

In [102]:
x1 = np.array([1, 2, 3, 0, 0])
y1 = np.array([
    [7, 0, 0, 0, 0],
    [8, 7, 0, 0, 0],
    [9, 8, 7, 0, 0],
    [0, 9, 8, 7, 0],
    [0, 0, 9, 8, 7],
])

In [103]:
np.matmul(y1, x1)

array([ 7, 22, 46, 42, 27])

In [ ]:
# np.matmul(np.pad(x, (1,1)).reshape(5, 1), np.pad(y, (1,1)).reshape(1, 5))

array([[ 0,  0,  0,  0,  0],
       [ 0,  7,  8,  9,  0],
       [ 0, 14, 16, 18,  0],
       [ 0, 21, 24, 27,  0],
       [ 0,  0,  0,  0,  0]])

In [25]:
24+18

42

In [27]:
np.pad(x, (1,1))

array([0, 1, 2, 3, 0])