In [1]:
import itertools

import sympy as sy
import numpy as np

In [33]:
di = sy.symbols(" ".join(f"d{i}"for i in range(3)))
di

(d0, d1, d2)

In [34]:
gi = sy.symbols(" ".join(f"g{i}"for i in range(2)))
gi

(g0, g1)

In [38]:
conv= sy.Matrix(np.convolve(gi, di))
conv

Matrix([
[        d0*g0],
[d0*g1 + d1*g0],
[d1*g1 + d2*g0],
[        d2*g1]])

In [41]:
conv.cholesky()

NonSquareMatrixError: Matrix must be square.

Tamanho dos vetores

In [2]:
td = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 1],
    [0, 0, 1]
])

In [3]:
np.linalg.svd(td)

(array([[-0.27059805,  0.5       , -0.65328148, -0.5       ],
        [-0.65328148,  0.5       ,  0.27059805,  0.5       ],
        [-0.65328148, -0.5       ,  0.27059805, -0.5       ],
        [-0.27059805, -0.5       , -0.65328148,  0.5       ]]),
 array([1.84775907, 1.41421356, 0.76536686]),
 array([[-5.00000000e-01, -7.07106781e-01, -5.00000000e-01],
        [ 7.07106781e-01,  3.20576898e-15, -7.07106781e-01],
        [-5.00000000e-01,  7.07106781e-01, -5.00000000e-01]]))

In [4]:
tg = np.array([
    [0, 1],
    [1, 1],
    [1, 1],
    [0, 1]
])

In [5]:
np.linalg.svd(tg)

(array([[-0.37174803,  0.60150096, -0.23570226, -0.66666667],
        [-0.60150096, -0.37174803, -0.66666667,  0.23570226],
        [-0.60150096, -0.37174803,  0.66666667, -0.23570226],
        [-0.37174803,  0.60150096,  0.23570226,  0.66666667]]),
 array([2.28824561, 0.87403205]),
 array([[-0.52573111, -0.85065081],
        [-0.85065081,  0.52573111]]))

In [6]:
from smithnormalform import matrix, snfproblem, z

In [23]:
td = [
    1, 0, 0,
    1, 1, 0,
    0, 1, 1,
    0, 0, 1
]
td

[1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1]

In [24]:
td = [z.Z(i) for i in td]
original_matrix = matrix.Matrix(4, 3, td)
print(original_matrix)

[1 0 0]
[1 1 0]
[0 1 1]
[0 0 1]



In [25]:
prob = snfproblem.SNFProblem(original_matrix)
prob.computeSNF()

In [26]:
prob.isValid()

True

In [27]:
print(prob.A)

[1 0 0]
[1 1 0]
[0 1 1]
[0 0 1]



In [28]:
print(prob.J)

[1 0 0]
[0 1 0]
[0 0 1]
[0 0 0]



In [29]:
print(prob.T)

[0 0 1]
[1 0 0]
[0 1 0]



In [30]:
prob.S * prob.A * prob.T == prob.J

True

In [31]:
from sympy import Matrix, ZZ
from sympy.matrices.normalforms import smith_normal_form
m = Matrix([[12, 6, 4], [3, 9, 6], [2, 16, 14]])

Matrix([[1, 0, 0], [0, 10, 0], [0, 0, -30]])


In [32]:
smith_normal_form(m, domain=ZZ)

Matrix([
[1,  0,   0],
[0, 10,   0],
[0,  0, -30]])